global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'neonhub_app'
    static_configs:
      - targets: ['app:8000']
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

rule_files:
  - 'alert.rules.yml' 