name: CI with Docker Compose

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Run docker-compose
        run: docker-compose up -d --build

      # Optional: Run tests
      # - name: Run backend tests
      #   run: docker-compose exec backend pytest

      # - name: Run frontend tests
      #   run: docker-compose exec frontend npm run test

# Comments:
# - Secrets must be set in GitHub repo settings (not in .env)
# - Add/remove env vars as needed for your config
# - Health endpoint must exist at /health for smoke test
# - Logs are saved to .github/logs/last_run.txt for debugging

# Add deployment steps for Vercel/Netlify/Render as needed 